version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app_clinic
    command: gunicorn src.main:app -b 0.0.0.0:8003 --workers 1 --worker-class uvicorn.workers.UvicornWorker
    ports:
      - 8888:8003