[tool.black]
line-length = 110
target-version = ['py311']
exclude = '''
    venv/
    tests/
    migrations/
'''

[tool.isort]
profile = "black"
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 110

[tool.autoflake]
check_diff = true
imports = ["sqlalchemy", "src", "fastapi", "typing", "auth", "patient", "patient_records"]

[tool.pyright]
include = ["src"]
