"""Add ill columns

Revision ID: 7487d8b4b6c9
Revises: 74c39748dbab
Create Date: 2024-02-10 15:29:27.422346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7487d8b4b6c9'
down_revision: Union[str, None] = '74c39748dbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('bp', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('ischemia', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('dep', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'dep')
    op.drop_column('patients', 'ischemia')
    op.drop_column('patients', 'bp')
    # ### end Alembic commands ###
