"""Add null options to Patient fields

Revision ID: a00dfcdf969e
Revises: d5871867d8de
Create Date: 2024-02-09 22:00:34.808429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00dfcdf969e'
down_revision: Union[str, None] = 'd5871867d8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'living_place',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'diagnosis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'first_visit',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patients', 'last_visit',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('patients', 'treatment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'inhabited_locality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'therapist_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'therapist_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'inhabited_locality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'treatment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'last_visit',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('patients', 'first_visit',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('patients', 'diagnosis',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'living_place',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
