"""Divide visit fields; Set default values to user bool params

Revision ID: c9ab5231c7f3
Revises: f3f0f1ca3fc2
Create Date: 2024-03-08 20:27:44.880041

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9ab5231c7f3'
down_revision: Union[str, None] = 'f3f0f1ca3fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_records', sa.Column('visit', sa.String(), nullable=True))
    op.drop_column('patient_records', 'last_visit')
    op.drop_column('patient_records', 'first_visit')
    op.alter_column('users', 'is_superuser', server_default=sa.text('false'))
    op.alter_column('users', 'is_active', server_default=sa.text('true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)
    op.add_column('patient_records', sa.Column('first_visit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('patient_records', sa.Column('last_visit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient_records', 'visit')
    # ### end Alembic commands ###
