"""Enhance ondelete params

Revision ID: cb83bc5fe862
Revises: 98d8176baad3
Create Date: 2024-03-20 11:06:51.670275

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cb83bc5fe862"
down_revision: Union[str, None] = "98d8176baad3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("patient_records_patient_id_fkey", "patient_records", type_="foreignkey")
    op.create_foreign_key(None, "patient_records", "patients", ["patient_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "patient_records", type_="foreignkey")
    op.create_foreign_key(
        "patient_records_patient_id_fkey",
        "patient_records",
        "patients",
        ["patient_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
