"""Add therapist field

Revision ID: d5871867d8de
Revises: 9e49fec97743
Create Date: 2024-02-09 11:59:42.775574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5871867d8de'
down_revision: Union[str, None] = '9e49fec97743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('therapist_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'patients', 'users', ['therapist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'therapist_id')
    # ### end Alembic commands ###
